[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  
# Redirects and headers are optional
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 