[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "docs/.vitepress/dist"

# Node.js environment configuration
[build.environment]
  # Use Node.js 18
  NODE_VERSION = "18"
  # VitePress requires legacy peer deps flag
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect for SPA (Single Page Application) navigation
# This ensures all routes are handled by the client-side router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff" 